on: push

jobs:
  BUILD-CUSTOM-UBUNTU-IMAGE:

    runs-on: ubuntu-latest    
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2

    - name: AZURE LOGIN 
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: BUILD WEBAPP
    #   run: bash ${{ GITHUB.WORKSPACE }}/vmbuildscript.sh # Run ./mvnw -Pprod clean verify and copies built artifacts to  ${{ GITHUB.WORKSPACE }}/target

    - name: BUILD-CUSTOM-VM-IMAGE  
      id: imageBuilder    
      uses: azure/build-vm-image@v0
      with:        
        resource-group-name: 'vmsonarm'
        managed-identity: 'vmsonarm'
        location: 'eastus2'
        source-os-type: 'linux'        
        source-image: canonical:0001-com-ubuntu-server-focal:20_04-lts-arm64:latest    
        customizer-source: '${{ GITHUB.WORKSPACE }}/'  # This folder gets copied to the image at root
        customizer-script: |
          bash ${{ GITHUB.WORKSPACE }}/vmbuildscript.sh
        dist-type: 'SharedImageGallery'
        dist-resource-id: '/subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/vmsonarm/providers/Microsoft.Compute/galleries/vmsonarm/images/vmsonarm'
        dist-location: 'eastus2'
          
        
